# Form implementation generated from reading ui file 'GSui.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

import os
from PyQt6 import QtCore, QtGui, QtWidgets
from pyqtgraph import PlotWidget


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 675)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setContentsMargins(20, 10, 20, 10)
        self.verticalLayout_4.setSpacing(20)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(4)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.logo = QtWidgets.QLabel(parent=self.centralwidget)
        self.logo.setText("")
        self.image_path = os.path.join(
            os.path.dirname(__file__), "images", "logo_resized.png"
        )
        self.logo.setPixmap(QtGui.QPixmap(self.image_path))
        self.logo.setObjectName("logo")
        self.gridLayout_4.addWidget(self.logo, 0, 0, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout_4)
        spacerItem = QtWidgets.QSpacerItem(
            40,
            20,
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Minimum,
        )
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.mission_time = QtWidgets.QLabel(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Preferred,
            QtWidgets.QSizePolicy.Policy.Preferred,
        )
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(6)
        sizePolicy.setHeightForWidth(self.mission_time.sizePolicy().hasHeightForWidth())
        self.mission_time.setSizePolicy(sizePolicy)
        self.mission_time.setStyleSheet(
            "QLabel {\n"
            "    background-color: rgb(100,100,100);\n"
            "    border-radius: 5px;\n"
            "    padding: 1px;\n"
            "    color: white;\n"
            "    font-size: 8 px;\n"
            "}\n"
            ""
        )
        self.mission_time.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.mission_time.setObjectName("mission_time")
        self.verticalLayout.addWidget(self.mission_time)
        self.flight_phase = QtWidgets.QLabel(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Preferred,
            QtWidgets.QSizePolicy.Policy.Preferred,
        )
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(4)
        sizePolicy.setHeightForWidth(self.flight_phase.sizePolicy().hasHeightForWidth())
        self.flight_phase.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.flight_phase.setFont(font)
        self.flight_phase.setStyleSheet(
            "QLabel {\n"
            "    background-color: rgb(255, 0, 0);\n"
            "    border-radius: 5px;\n"
            "    padding: 1px;\n"
            "    color: white;\n"
            "}\n"
            ""
        )
        self.flight_phase.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.flight_phase.setObjectName("flight_phase")
        self.verticalLayout.addWidget(self.flight_phase)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.IMU_error = QtWidgets.QLabel(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Preferred,
            QtWidgets.QSizePolicy.Policy.Preferred,
        )
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(4)
        sizePolicy.setHeightForWidth(self.IMU_error.sizePolicy().hasHeightForWidth())
        self.IMU_error.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.IMU_error.setFont(font)
        self.IMU_error.setStyleSheet(
            "QLabel {\n"
            "    background-color: rgb(255, 0, 0);\n"
            "    border-radius: 5px;\n"
            "    padding: 1px;\n"
            "    color: white;\n"
            "}\n"
            ""
        )
        self.IMU_error.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.IMU_error.setObjectName("IMU_error")
        self.verticalLayout_3.addWidget(self.IMU_error)
        self.GPS_error = QtWidgets.QLabel(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Preferred,
            QtWidgets.QSizePolicy.Policy.Preferred,
        )
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(4)
        sizePolicy.setHeightForWidth(self.GPS_error.sizePolicy().hasHeightForWidth())
        self.GPS_error.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.GPS_error.setFont(font)
        self.GPS_error.setStyleSheet(
            "QLabel {\n"
            "    background-color: rgb(255, 0, 0);\n"
            "    border-radius: 5px;\n"
            "    padding: 1px;\n"
            "    color: white;\n"
            "}\n"
            ""
        )
        self.GPS_error.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.GPS_error.setObjectName("GPS_error")
        self.verticalLayout_3.addWidget(self.GPS_error)
        self.ALT_error = QtWidgets.QLabel(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Preferred,
            QtWidgets.QSizePolicy.Policy.Preferred,
        )
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(4)
        sizePolicy.setHeightForWidth(self.ALT_error.sizePolicy().hasHeightForWidth())
        self.ALT_error.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ALT_error.setFont(font)
        self.ALT_error.setStyleSheet(
            "QLabel {\n"
            "    background-color: rgb(255, 0, 0);\n"
            "    border-radius: 5px;\n"
            "    padding: 1px;\n"
            "    color: white;\n"
            "}\n"
            ""
        )
        self.ALT_error.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.ALT_error.setObjectName("ALT_error")
        self.verticalLayout_3.addWidget(self.ALT_error)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        spacerItem1 = QtWidgets.QSpacerItem(
            40,
            20,
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Minimum,
        )
        self.horizontalLayout.addItem(spacerItem1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.voltage = QtWidgets.QLabel(parent=self.centralwidget)
        self.voltage.setStyleSheet("color: rgb(255,255,255)")
        self.voltage.setObjectName("voltage")
        self.gridLayout_2.addWidget(self.voltage, 2, 0, 1, 1)
        self.data_rate = QtWidgets.QLabel(parent=self.centralwidget)
        self.data_rate.setStyleSheet("color: rgb(255,255,255)")
        self.data_rate.setObjectName("data_rate")
        self.gridLayout_2.addWidget(self.data_rate, 0, 0, 1, 1)
        self.alt = QtWidgets.QLabel(parent=self.centralwidget)
        self.alt.setStyleSheet("color: rgb(255,255,255)")
        self.alt.setObjectName("alt")
        self.gridLayout_2.addWidget(self.alt, 3, 2, 1, 1)
        self.voltage_val = QtWidgets.QLabel(parent=self.centralwidget)
        self.voltage_val.setStyleSheet("color: rgb(255,255,255)")
        self.voltage_val.setObjectName("voltage_val")
        self.gridLayout_2.addWidget(self.voltage_val, 2, 1, 1, 1)
        self.data_rate_val = QtWidgets.QLabel(parent=self.centralwidget)
        self.data_rate_val.setStyleSheet("color: rgb(255,255,255)")
        self.data_rate_val.setObjectName("data_rate_val")
        self.gridLayout_2.addWidget(self.data_rate_val, 0, 1, 1, 1)
        self.lon = QtWidgets.QLabel(parent=self.centralwidget)
        self.lon.setStyleSheet("color: rgb(255,255,255)")
        self.lon.setObjectName("lon")
        self.gridLayout_2.addWidget(self.lon, 2, 2, 1, 1)
        self.lon_val = QtWidgets.QLabel(parent=self.centralwidget)
        self.lon_val.setStyleSheet("color: rgb(255,255,255)")
        self.lon_val.setObjectName("lon_val")
        self.gridLayout_2.addWidget(self.lon_val, 2, 3, 1, 1)
        self.RSSI = QtWidgets.QLabel(parent=self.centralwidget)
        self.RSSI.setStyleSheet("color: rgb(255,255,255)")
        self.RSSI.setObjectName("RSSI")
        self.gridLayout_2.addWidget(self.RSSI, 3, 0, 1, 1)
        self.lat_val = QtWidgets.QLabel(parent=self.centralwidget)
        self.lat_val.setStyleSheet("color: rgb(255,255,255)")
        self.lat_val.setObjectName("lat_val")
        self.gridLayout_2.addWidget(self.lat_val, 1, 3, 1, 1)
        self.pyros_val = QtWidgets.QLabel(parent=self.centralwidget)
        self.pyros_val.setStyleSheet("color: rgb(255,255,255)")
        self.pyros_val.setObjectName("pyros_val")
        self.gridLayout_2.addWidget(self.pyros_val, 0, 3, 1, 1)
        self.packet_age = QtWidgets.QLabel(parent=self.centralwidget)
        self.packet_age.setStyleSheet("color: rgb(255,255,255)")
        self.packet_age.setObjectName("packet_age")
        self.gridLayout_2.addWidget(self.packet_age, 1, 0, 1, 1)
        self.lat = QtWidgets.QLabel(parent=self.centralwidget)
        self.lat.setStyleSheet("color: rgb(255,255,255)")
        self.lat.setObjectName("lat")
        self.gridLayout_2.addWidget(self.lat, 1, 2, 1, 1)
        self.RSSI_val = QtWidgets.QLabel(parent=self.centralwidget)
        self.RSSI_val.setStyleSheet("color: rgb(255,255,255)")
        self.RSSI_val.setObjectName("RSSI_val")
        self.gridLayout_2.addWidget(self.RSSI_val, 3, 1, 1, 1)
        self.pyros = QtWidgets.QLabel(parent=self.centralwidget)
        self.pyros.setStyleSheet("color: rgb(255, 255, 255);")
        self.pyros.setObjectName("pyros")
        self.gridLayout_2.addWidget(self.pyros, 0, 2, 1, 1)
        self.packet_age_val = QtWidgets.QLabel(parent=self.centralwidget)
        self.packet_age_val.setStyleSheet("color: rgb(255, 255, 255);")
        self.packet_age_val.setObjectName("packet_age_val")
        self.gridLayout_2.addWidget(self.packet_age_val, 1, 1, 1, 1)
        self.alt_val = QtWidgets.QLabel(parent=self.centralwidget)
        self.alt_val.setStyleSheet("color: rgb(255,255,255)")
        self.alt_val.setObjectName("alt_val")
        self.gridLayout_2.addWidget(self.alt_val, 3, 3, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout_2)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.connect_toggle = QtWidgets.QPushButton(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Preferred,
            QtWidgets.QSizePolicy.Policy.Preferred,
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.connect_toggle.sizePolicy().hasHeightForWidth()
        )
        self.connect_toggle.setSizePolicy(sizePolicy)
        self.connect_toggle.setStyleSheet(
            "background-color: rgb(100,100,100);\n"
            "border-radius: 5px;\n"
            "padding: 1px;\n"
            "color: white;\n"
            "font-size: 8 px;\n"
            ""
        )
        self.connect_toggle.setObjectName("connect_toggle")
        self.verticalLayout_2.addWidget(self.connect_toggle)
        self.mission_start_toggle = QtWidgets.QPushButton(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Preferred,
            QtWidgets.QSizePolicy.Policy.Preferred,
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.mission_start_toggle.sizePolicy().hasHeightForWidth()
        )
        self.mission_start_toggle.setSizePolicy(sizePolicy)
        self.mission_start_toggle.setStyleSheet(
            "background-color: rgb(100,100,100);\n"
            "border-radius: 5px;\n"
            "padding: 1px;\n"
            "color: white;\n"
            "font-size: 8 px;\n"
            ""
        )
        self.mission_start_toggle.setObjectName("mission_start_toggle")
        self.verticalLayout_2.addWidget(self.mission_start_toggle)
        self.save_data = QtWidgets.QPushButton(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Preferred,
            QtWidgets.QSizePolicy.Policy.Preferred,
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.save_data.sizePolicy().hasHeightForWidth())
        self.save_data.setSizePolicy(sizePolicy)
        self.save_data.setStyleSheet(
            "background-color: rgb(100,100,100);\n"
            "border-radius: 5px;\n"
            "padding: 1px;\n"
            "color: white;\n"
            "font-size: 8 px;\n"
            ""
        )
        self.save_data.setObjectName("save_data")
        self.verticalLayout_2.addWidget(self.save_data)
        self.autosave_toggle = QtWidgets.QPushButton(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Preferred,
            QtWidgets.QSizePolicy.Policy.Preferred,
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.autosave_toggle.sizePolicy().hasHeightForWidth()
        )
        self.autosave_toggle.setSizePolicy(sizePolicy)
        self.autosave_toggle.setStyleSheet(
            "background-color: rgb(100,100,100);\n"
            "border-radius: 5px;\n"
            "padding: 1px;\n"
            "color: white;\n"
            "font-size: 8 px;\n"
            ""
        )
        self.autosave_toggle.setObjectName("autosave_toggle")
        self.verticalLayout_2.addWidget(self.autosave_toggle)
        self.clear_data = QtWidgets.QPushButton(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Preferred,
            QtWidgets.QSizePolicy.Policy.Preferred,
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clear_data.sizePolicy().hasHeightForWidth())
        self.clear_data.setSizePolicy(sizePolicy)
        self.clear_data.setStyleSheet(
            "background-color: rgb(100,100,100);\n"
            "border-radius: 5px;\n"
            "padding: 1px;\n"
            "color: white;\n"
            "font-size: 8 px;\n"
            ""
        )
        self.clear_data.setObjectName("clear_data")
        self.verticalLayout_2.addWidget(self.clear_data)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.mission_log = QtWidgets.QLabel(parent=self.centralwidget)
        self.mission_log.setStyleSheet("\n" "color: white;\n" "font-size: 8 px;\n" "")
        self.mission_log.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.mission_log.setObjectName("mission_log")
        self.verticalLayout_8.addWidget(self.mission_log)
        self.log_entry = QtWidgets.QPlainTextEdit(parent=self.centralwidget)
        self.log_entry.setStyleSheet("color: white;\n" "font-size: 8 px;\n" "")
        self.log_entry.setReadOnly(True)
        self.log_entry.setObjectName("log_entry")
        self.verticalLayout_8.addWidget(self.log_entry)
        self.horizontalLayout.addLayout(self.verticalLayout_8)
        self.horizontalLayout.setStretch(0, 20)
        self.horizontalLayout.setStretch(1, 2)
        self.horizontalLayout.setStretch(2, 20)
        self.horizontalLayout.setStretch(3, 10)
        self.horizontalLayout.setStretch(4, 15)
        self.horizontalLayout.setStretch(5, 50)
        self.horizontalLayout.setStretch(6, 20)
        self.horizontalLayout.setStretch(7, 30)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.Plot4 = PlotWidget(parent=self.centralwidget)
        self.Plot4.setObjectName("Plot4")
        self.gridLayout.addWidget(self.Plot4, 1, 0, 1, 1)
        self.Plot5 = PlotWidget(parent=self.centralwidget)
        self.Plot5.setObjectName("Plot5")
        self.gridLayout.addWidget(self.Plot5, 1, 1, 1, 1)
        self.Plot6 = PlotWidget(parent=self.centralwidget)
        self.Plot6.setObjectName("Plot6")
        self.gridLayout.addWidget(self.Plot6, 1, 2, 1, 1)
        self.Plot3 = PlotWidget(parent=self.centralwidget)
        self.Plot3.setObjectName("Plot3")
        self.gridLayout.addWidget(self.Plot3, 0, 2, 1, 1)
        self.Plot1 = PlotWidget(parent=self.centralwidget)
        self.Plot1.setObjectName("Plot1")
        self.gridLayout.addWidget(self.Plot1, 0, 0, 1, 1)
        self.Plot2 = PlotWidget(parent=self.centralwidget)
        self.Plot2.setObjectName("Plot2")
        self.gridLayout.addWidget(self.Plot2, 0, 1, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout)
        self.verticalLayout_4.setStretch(0, 20)
        self.verticalLayout_4.setStretch(1, 80)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.mission_time.setText(
            _translate(
                "MainWindow",
                '<html><head/><body><p align="center">Mission Time</p><p align="center"><a name="elapsedTime"/><span style=" font-size:12pt;">0</span><span style=" font-size:12pt;">0:00:00</span></p></body></html>',
            )
        )
        self.flight_phase.setText(_translate("MainWindow", "PHASE"))
        self.IMU_error.setText(_translate("MainWindow", "IMU"))
        self.GPS_error.setText(_translate("MainWindow", "GPS"))
        self.ALT_error.setText(_translate("MainWindow", "ALT"))
        self.voltage.setText(_translate("MainWindow", "Voltage:"))
        self.data_rate.setText(_translate("MainWindow", "Data Rate:"))
        self.alt.setText(_translate("MainWindow", "GPS Alt:"))
        self.voltage_val.setText(_translate("MainWindow", "NaN"))
        self.data_rate_val.setText(_translate("MainWindow", "NaN"))
        self.lon.setText(_translate("MainWindow", "GPS Lon:"))
        self.lon_val.setText(_translate("MainWindow", "NaN"))
        self.RSSI.setText(_translate("MainWindow", "RSSI:"))
        self.lat_val.setText(_translate("MainWindow", "NaN"))
        self.pyros_val.setText(_translate("MainWindow", "NaN"))
        self.packet_age.setText(_translate("MainWindow", "Packet Age:"))
        self.lat.setText(_translate("MainWindow", "GPS Lat:"))
        self.RSSI_val.setText(_translate("MainWindow", "NaN"))
        self.pyros.setText(_translate("MainWindow", "Pyros:"))
        self.packet_age_val.setText(_translate("MainWindow", "NaN"))
        self.alt_val.setText(_translate("MainWindow", "NaN"))
        self.connect_toggle.setText(_translate("MainWindow", "Connect"))
        self.mission_start_toggle.setText(_translate("MainWindow", "Start Recording"))
        self.save_data.setText(_translate("MainWindow", "Save Data"))
        self.autosave_toggle.setText(_translate("MainWindow", "Auto Save: Off"))
        self.clear_data.setText(_translate("MainWindow", "Clear Data"))
        self.mission_log.setText(_translate("MainWindow", "Mission Log"))
